version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:latest
      - image: circleci/mysql:latest
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --default-authentication-plugin=mysql_native_password
        environment:
          MYSQL_ROOT_PASSWORD: rootpw
          MYSQL_DATABASE: dev
          MYSQL_USER: dev
          MYSQL_PASSWORD: passw0rd
    working_directory: /go/src/agokit
    steps:
      - checkout
      - run:
          name: Install tools
          command: |
            go get -v github.com/rubenv/sql-migrate/...
      - run:
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
            nc -z 127.0.0.1 3306 && echo Success && exit 0
            echo -n .
            sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run:
          name: Migrate
          command: |
            chmod +x /go/src/agokit/db/migrate.sh
            cd /go/src/agokit/db
            ./migrate.sh
      - run:
          name: Download Packages
          command: |
            go get -v -t -d ./...
      - run:
          name: Download Vendor
          command: |
            go mod vendor
      - run:
          name: Test
          command: |
            go test -v -cover ./...